"""
Some notes:
1. For simplicity reasons the app support only one date per user per activity type. (e.g., one physical activity per day)
2. The date format should be in the format YYYY-MM-DD
3. The API is designed to be used with a database, so the user_id should be autogenerated by the database.
4. The API is designed with multiple updated in a day although it is not possible in the current design.
"""


